In [11]:
import json
import numpy as np
import pandas as pd

In [5]:
with open('example_02.truss', 'r') as myfile:
    data=myfile.read()

In [6]:
obj = json.loads(data)

In [7]:
nn = len(obj["nodes"])
nodos = np.zeros((nn,2))
for i,m in enumerate(obj["nodes"]):
    nodos[i,0] = m["x"]
    nodos[i,1] = m["y"]

In [8]:
nn = len(obj["elements"])
elementos = np.zeros((nn,4))
for i,m in enumerate(obj["elements"]):
    elementos[i,0] = m["ni"]
    elementos[i,1] = m["nj"]
    elementos[i,2] = m["E"]
    elementos[i,3] = m["A"]
    
elementos

array([[1.e+00, 2.e+00, 2.e+11, 1.e-04],
       [2.e+00, 3.e+00, 2.e+11, 1.e-04],
       [3.e+00, 4.e+00, 2.e+11, 1.e-04],
       [4.e+00, 5.e+00, 2.e+11, 1.e-04],
       [5.e+00, 6.e+00, 2.e+11, 1.e-04],
       [1.e+00, 6.e+00, 2.e+11, 1.e-04],
       [2.e+00, 5.e+00, 2.e+11, 1.e-04],
       [2.e+00, 6.e+00, 2.e+11, 1.e-04],
       [2.e+00, 4.e+00, 2.e+11, 1.e-04]])

In [9]:
nn = len(obj["constraints"])
const = np.zeros((nn,3))
for i,m in enumerate(obj["constraints"]):
    const[i,1] = np.nan if m["ux"] == "free" else m["ux"]
    const[i,2] = np.nan if m["uy"] == "free" else m["uy"]
    const[i,0] = m["node"]
    
const

array([[ 1.,  0.,  0.],
       [ 3., nan,  0.]])

In [10]:
nn = len(obj["forces"])
fuerzas = np.zeros((nn,3))
for i,m in enumerate(obj["forces"]):
    fuerzas[i,1] = m["fx"]
    fuerzas[i,2] = m["fy"]
    fuerzas[i,0] = m["node"]
    
fuerzas

array([[    4.,     0., -3000.],
       [    5.,     0., -4000.],
       [    6.,     0., -3000.]])

In [14]:
fz = pd.DataFrame(fuerzas)

In [22]:
fz.to_html(justify="center")

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: center;">\n      <th></th>\n      <th>0</th>\n      <th>1</th>\n      <th>2</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>4.0</td>\n      <td>0.0</td>\n      <td>-3000.0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>5.0</td>\n      <td>0.0</td>\n      <td>-4000.0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>6.0</td>\n      <td>0.0</td>\n      <td>-3000.0</td>\n    </tr>\n  </tbody>\n</table>'

<table border="10" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>0</th>\n      <th>1</th>\n      <th>2</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>4.0</td>\n      <td>0.0</td>\n      <td>-3000.0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>5.0</td>\n      <td>0.0</td>\n      <td>-4000.0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>6.0</td>\n      <td>0.0</td>\n      <td>-3000.0</td>\n    </tr>\n  </tbody>\n</table>